services:
  apisix:
    build: .
    container_name: apisix-standalone
    restart: unless-stopped
    volumes:
      - ./conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080"   # HTTP
      - "9443:9443"   # HTTPS 
