apisix:
  node_listen: 9080
  enable_ipv6: false

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

  admin:
    enable_admin_cors: false

# Standalone file-based configuration
standalone:
  config_file: /usr/local/apisix/conf/apisix.yaml
  poll_interval: 1

nginx_config:
  error_log: /dev/stderr
  access_log: /dev/stdout
